eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}

spring:
  data:
    redis:
      url: ${REDIS.URL}
  config:
    import: file:auth-service/.env.dev.yml
  kafka:
    bootstrap-servers: ${KAFKA.BOOTSTRAP_SERVERS}

keycloak:
  realm: ${KEYCLOAK.REALM}
  resource: ${KEYCLOAK.RESOURCE}
  credentials:
    client-id: ${KEYCLOAK.CREDENTIALS.CLIENT_ID}
    secret: ${KEYCLOAK.CREDENTIALS.SECRET}
  auth-server-url: ${KEYCLOAK.AUTH_SERVER_URL}
  jwks-certs: ${KEYCLOAK.JWKS_CERTS}