server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      file: ./auth-service/docker-compose.yaml
  application:
    name: auth-service

  kafka:
    bootstrap-servers: kafka:9092

keycloak:
  jwks-certs: http://keycloak:8180/realms/fablewhirl-realm/protocol/openid-connect/certs
  realm: fablewhirl-realm
  auth-server-url: http://keycloak:8180/
  resource: auth-service
  credentials:
    client-id: auth-service
    secret: sf3a2PDVId7fqA5TYr9UEhvb4krPR0K0
  use-resource-role-mappings: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8095/eureka/

management:
  endpoints:
    web:
      exposure:
        include: prometheus