server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  docker:
    compose:
      file: ./auth-service/docker-compose.yaml
  application:
    name: auth-service

  kafka:
    bootstrap-servers: localhost:9092

keycloak:
  realm: fablewhirl-realm
  auth-server-url: http://localhost:9090/realms/fablewhirl-realm/protocol/openid-connect/auth
  resource: auth-service
  credentials:
    secret: KtBLS3ANnpNAdcwJmYXC5jvRrxjviexX
  use-resource-role-mappings: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8095/eureka/