eureka:
  instance:
    hostname: auth-service.fablewhirl.svc.cluster.local
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  kafka:
    bootstrap-servers: kafka:9092

keycloak:
  jwks-certs: http://keycloak:8443/realms/fablewhirl-realm/protocol/openid-connect/certs
  auth-server-url: http://keycloak:8443/
