eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  kafka:
    bootstrap-servers: localhost:9092

keycloak:
  jwks-certs: http://localhost:8443/realms/fablewhirl-realm/protocol/openid-connect/certs
  auth-server-url: http://localhost:8443/