server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  docker:
    compose:
      file: ./auth-service/docker-compose.yaml
  application:
    name: auth-service

  kafka:
    bootstrap-servers: localhost:9092

keycloak:
  jwks-certs: http://localhost:9090/realms/fablewhirl-realm/protocol/openid-connect/certs
  realm: fablewhirl-realm
  auth-server-url: http://localhost:9090/
  resource: auth-service
  credentials:
    client-id: auth-service
    secret: A6YFJ8fhZVbEMg26stWF8S6dpYYHByCz
  use-resource-role-mappings: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8095/eureka/

management:
  endpoints:
    web:
      exposure:
        include: prometheus