server:
  port: 8091

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true

keycloak:
  use-resource-role-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus