server:
  port: 8091

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true

keycloak:
  realm: fablewhirl-realm
  resource: auth-service
  credentials:
    client-id: auth-service
    secret: sf3a2PDVId7fqA5TYr9UEhvb4krPR0K0
  use-resource-role-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus