services:

  mongo:
    image: mongo:latest
    container_name: comment-data
    command: mongod --port 27020
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27020:27020"
    restart: unless-stopped

volumes:
  mongo-data:
