server:
  port: 8095

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: thread-service
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus
