eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/fablewhirl-realm
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/comment-data?authSource=admin

keycloak:
  jwks-certs: http://localhost:8443/realms/fablewhirl-realm/protocol/openid-connect/certs