server:
  port: 8085

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8180/realms/fablewhirl-realm


  application:
    name: thread-service

  data:
    mongodb:
      uri: mongodb://admin:secret@mongo-comment-data:27020/comment_data

eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8095/eureka/


management:
  endpoints:
    web:
      exposure:
        include: prometheus

keycloak:
  jwks-certs: http://auth-service:8180/realms/fablewhirl-realm/protocol/openid-connect/certs