server:
  port: 8085

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/fablewhirl-realm


  application:
    name: thread-service

  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/comment_data

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8095/eureka/


management:
  endpoints:
    web:
      exposure:
        include: prometheus

keycloak:
  jwks-certs: http://localhost:8080/realms/fablewhirl-realm/protocol/openid-connect/certs