eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}

spring:
  config:
    import: file:api-gateway/.env.dev.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}