server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/fablewhirl

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
resilience4j:
  retry:
    configs:
      default:
        wait-duration: 2s
        max-attempts: '3'
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: '50'
        register-health-indicator: 'true'
        sliding-window-type: COUNT_BASED
        automatic-transition-from-open-to-half-open-enabled: 'true'
        sliding-window-size: '10'
        minimum-number-of-calls: '5'
        permitted-number-of-calls-in-half-open-state: '3'
        wait-duration-in-open-state: 5s
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
