eureka:
  instance:
    hostname: gateway.turron.svc.cluster.local
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8443/realms/fablewhirl-realm
