services:
  mongo:
    image: mongo:latest
    container_name: character-media
    command: mongod --port 27018
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27018:27018"
    restart: unless-stopped

volumes:
  mongo-data: