global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:3000' ]
        labels:
          application: 'Api Gateway'

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8091' ]
        labels:
          application: 'Auth Service'

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8092' ]
        labels:
          application: 'User Service'

  - job_name: 'character-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8093' ]
        labels:
          application: 'Character Service'

  - job_name: 'thread-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8094' ]
        labels:
          application: 'Thread Service'

  - job_name: 'comment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8095' ]
        labels:
          application: 'Comment Service'