server:
  port: 8083
spring:
  application:
    name: character-service
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27018/character_data

  kafka:
    producer:
      bootstrap-servers: localhost:9092


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8095/eureka/