eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}

spring:
  config:
    import: file:character-service/.env.dev.yml
  kafka:
    bootstrap-servers: ${KAFKA.BOOTSTRAP_SERVERS}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  data:
    mongodb:
      uri: ${MONGODB.URI}

keycloak:
  jwks-certs: ${KEYCLOAK.JWKS_CERTS}