server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27018/character_data
  application:
    name: character-service

  kafka:
    producer:
      bootstrap-servers: localhost:9092

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/fablewhirl-realm

keycloak:
  jwks-certs: http://localhost:8180/realms/fablewhirl-realm/protocol/openid-connect/certs

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8095/eureka/


management:
  endpoints:
    web:
      exposure:
        include: prometheus