server:
  port: 8093

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: character-service
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus