eureka:
  instance:
    hostname: character-server.fablewhirl.svc.cluster.local
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8443/realms/fablewhirl-realm
  data:
    mongodb:
      uri: mongodb://admin:secret@mongodb:27017/character-data?authSource=admin

keycloak:
  jwks-certs: http://keycloak:8443/realms/fablewhirl-realm/protocol/openid-connect/certs