apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-service
  template:
    metadata:
      labels:
        app: character-service
    spec:
      containers:
        - name: character-service
          image: ghcr.io/fl1s/character-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: character-service
spec:
  selector:
    app: character-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP