apiVersion: v1
kind: Secret
metadata:
  name: mongo-user-media-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-user-media
spec:
  serviceName: "mongo-user-media"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-user-media
  template:
    metadata:
      labels:
        app: mongo-user-media
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-user-media-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-user-media-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-user-media
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-user-media