apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'api-gateway:3000' ]
            labels:
              application: 'Api Gateway Application'

      - job_name: 'auth-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'auth-service:8081' ]
            labels:
              application: 'Auth Service Application'

      - job_name: 'user-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'user-service:8082' ]
            labels:
              application: 'User Service Application'

      - job_name: 'character-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'character-service:8083' ]
            labels:
              application: 'Character Service Application'

      - job_name: 'thread-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'thread-service:8084' ]
            labels:
              application: 'Thread Service Application'

      - job_name: 'comment-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'comment-service:8085' ]
            labels:
              application: 'Comment Service Application'
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus