apiVersion: apps/v1
kind: Deployment
metadata:
  name: thread-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thread-service
  template:
    metadata:
      labels:
        app: thread-service
    spec:
      containers:
        - name: thread-service
          image: ghcr.io/fl1s/thread-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: thread-service
spec:
  selector:
    app: thread-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP