server:
  port: 8084

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8180/realms/fablewhirl-realm

  application:
    name: thread-service

  data:
    mongodb:
      uri: mongodb://admin:secret@mongo:27017/thread_data

eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8095/eureka/

keycloak:
  jwks-certs: http://auth-service:8180/realms/fablewhirl-realm/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: prometheus