eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}

spring:
  config:
    import: file:thread-service/.env.prod.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  data:
    redis:
      url: ${REDIS.URL}
    mongodb:
      uri: ${MONGODB.URI}

keycloak:
  jwks-certs: ${KEYCLOAK.JWKS_CERTS}