apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: fablewhirl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.0
          ports:
            - containerPort: 8443
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start-dev"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "secret"
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "600m"
            limits:
              memory: "2Gi"
              cpu: "1"
          livenessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 120
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: fablewhirl
spec:
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    app: keycloak