eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/fablewhirl-realm
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://admin:secret@localhost:27017/user-media?authSource=admin

minio:
  bucket:
    name: users
  url: http://localhost:9000
  root-user: admin
  root-password: secret123

keycloak:
  jwks-certs: http://localhost:8443/realms/fablewhirl-realm/protocol/openid-connect/certs