eureka:
  instance:
    hostname: ${EUREKA.INSTANCE.HOSTNAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA.CLIENT.SERVICE_URL.DEFAULT_ZONE}

spring:
  config:
    import: file:user-service/.env.dev.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  kafka:
    bootstrap-servers: ${KAFKA.BOOTSTRAP_SERVERS}

  datasource:
    url: ${POSTGRES.DB_URL}
    username: ${POSTGRES.PG_USERNAME}
    password: ${POSTGRES.PG_PASSWORD}
    driver-class-name: ${POSTGRES.PG_DRIVER}
  data:
    mongodb:
      uri: ${MONGODB.URI}

minio:
  bucket:
    name: ${MINIO.BUCKET.NAME}
  url: ${MINIO.URL}
  root-user: ${MINIO.ROOT_USER}
  root-password: ${MINIO.ROOT_PASSWORD}

keycloak:
  jwks-certs: ${KEYCLOAK.JWKS-CERTS}