server:
  port: '8082'
spring:
  application:
    name: user-service
  kafka:
    topic:
      name: user-registration
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: '*'

  datasource:
    url: jdbc:postgresql://localhost:5432/users-db
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

