version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=secret
    ports:
      - "8090:8080"
    command: start-dev
    depends_on:
       - redis


  redis:
    image: redis:latest
    container_name: tokens
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
