services:

  keycloak_web:
    container_name: keycloak_web
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=secret
    ports:
      - "9090:8080"
    command: start-dev