services:
  redis:
    image: redis:latest
    container_name: keycloak_hash
    restart: always
    ports:
      - "6379:6379"
    networks:
      - keycloak-network

  keycloak_web:
    container_name: keycloak_web
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=secret
    ports:
      - "9090:8080"
    command: start-dev
    depends_on:
      - redis

networks:
  keycloak-network:
    driver: bridge