apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: fablewhirl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: wait-for-eureka
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - 'until curl -s http://eureka-server:8761/eureka/apps > /dev/null; do echo "Waiting for Eureka Server..."; sleep 5; done'
      containers:
        - name: api-gateway
          imagePullPolicy: Always
          image: ghcr.io/fl1s/fablewhirl/api-gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: fablewhirl
spec:
  selector:
    app: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
