apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fablewhirl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/fl1s/auth-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "http://keycloak:8080/"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-server"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8095/eureka/"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fablewhirl
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: auth-service