apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-service
  namespace: fablewhirl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-service
  template:
    metadata:
      labels:
        app: character-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: character-service
          image: ghcr.io/fl1s/character-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://admin:secret@mongo:27017/character_data"
            - name: SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-server"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8095/eureka/"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://auth-service:8180/realms/fablewhirl-realm"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: character-service
  namespace: fablewhirl
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: character-service