apiVersion: apps/v1
kind: Deployment
metadata:
  name: character-service
  namespace: fablewhirl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: character-service
  template:
    metadata:
      labels:
        app: character-service
    spec:
      initContainers:
        - name: wait-for-eureka
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - 'until curl -s http://eureka-server:8761/eureka/apps > /dev/null; do echo "Waiting for Eureka Server..."; sleep 5; done'
      containers:
        - name: character-service
          imagePullPolicy: Always
          image: ghcr.io/fl1s/fablewhirl/character-service:latest
          ports:
            - containerPort: 8093
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: character-service
  namespace: fablewhirl
spec:
  selector:
    app: character-service
  ports:
    - port: 8093
      targetPort: 8093
