apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: fablewhirl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          imagePullPolicy: Always
          image: ghcr.io/fl1s/fablewhirl/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: fablewhirl
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
