apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: fablewhirl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: ghcr.io/fl1s/eureka-server:latest
          ports:
            - containerPort: 8095
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-server"
            - name: EUREKA_CLIENT_REGISTERWITHEUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCHREGISTRY
              value: "false"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8095/eureka/"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: fablewhirl
spec:
  ports:
    - port: 8095
      targetPort: 8095
  selector:
    app: eureka-server