version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: user-info
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=users-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - user-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: user-media
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    networks:
      - user-network
    restart: unless-stopped

networks:
  user-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data:
