version: '4'

services:

  mongo:
    image: mongo:latest
    container_name: thread-data
    command: mongod --port 27019
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27019:27019"
    restart: unless-stopped

volumes:
  mongo-data:
